name: Publish New Formula

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish-new-formula:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Clone repo
        run: git clone https://github.com/OwO-Network/homebrew-nexttrace-enhanced.git
      - run: cd homebrew-nexttrace-enhanced && bash genFormula.sh
      - name: List files in the repository
        run: |
          pwd
          ls .
      - run: echo "🍏 This job's status is ${{ job.status }}."
